### PR TITLE
feature: Automatically patch API :breaking:

### PR DESCRIPTION
**Pull request by DReigada**
This is a proposal for removing the manual "patching" of the swagger definition.
Currently we add 2 fields manually for "patching" the API:
1. `x-ms-parameter-location`
2. `x-ms-enum`

There's two ways of doing this:
### 1. This proposal
Which takes the api definition from the website and adds the fields specific to autorest in order to generate the API properly.
Pros:
- Does not require the website definition to know about autorest tags
Cons:
- Might break more easily if we don't define the API in the website in a way that we can add the fields automatically
- Requires the website to add a custom field to enums in order to use the same type for both query parameters and body types. I called it `x-type-name` but can be changed

### 2. Website proposal
Add fields specific to autorest to the API definition in the website.
Pros:
- Won't break easily since we add the fields manually in the website
Cons:
- The website needs to know about the autorest specific flags
- The api definition will be bloated with fields specific to one api generator

### CODE REVIEW

**Comment by rtfpessoa** [comment]
I honestly dislike this approach I would much rather have all the spec in one place with everything it needs for our setup.

**Comment by DReigada** [comment]
That leaves some questions though @rtfpessoa :
Should we have annotations in the definition for each generator we use?
If we create a ruby api that also requires annotations, should we add them in the definition too?
If we deprecate this API should we keep the annotations in the definition?

**Comment by rtfpessoa** [comment]
> Should we have annotations in the definition for each generator we use?

I see no problem, and the fact that it is there makes is explicit.

> If we create a ruby api that also requires annotations, should we add them in the definition too?

Why not?

> If we deprecate this API should we keep the annotations in the definition?

Not sure I get this point.

**Comment by DReigada** [comment]
> > Should we have annotations in the definition for each generator we use?
> 
> I see no problem, and the fact that it is there makes is explicit.
The problem is that we will have a lot of API annotations that are specific to a single code generator.
> > If we create a ruby api that also requires annotations, should we add them in the definition too?
> 
> Why not?
Same reason as above.
> > If we deprecate this API should we keep the annotations in the definition?
> 
> Not sure I get this point.
In the future we might move from autorest to another typescript code generator, if we do that, should we keep the annotations that are specific to autorest?

**Comment by rtfpessoa** [comment]
_Your quotes above were very hard to read_

> > > Should we have annotations in the definition for each generator we use?
> > > 
> > I see no problem, and the fact that it is there makes is explicit.
> > 
> The problem is that we will have a lot of API annotations that are specific to a single code 
generator.
> 
If we are using the generator and need them, why hide it? For me explicit always wins.

> > > If we create a ruby api that also requires annotations, should we add them in the definition too?
> > > 
> > Why not?
> > 
> Same reason as above.
> 
Same answer

> > > If we deprecate this API should we keep the annotations in the definition?
> > > 
> > Not sure I get this point.
> > 
> In the future we might move from autorest to another typescript code generator, if we do that, should we keep the annotations that are specific to autorest?
> 
Ok, I see. In that case, I would then remove them.
I see the file as a method to help us develop, so we should try to take profit from it.
Like old code, if not used anymore you can remove it.

**Comment by gjsduarte** [comment]
I agree that maybe we shouldn't try to optimize this for multiple generators yet. 
I wouldn't consider changing the API specification by removing or changing this sort of metadata as a breaking change.

**Comment by DReigada** [comment]
@rtfpessoa I agree that explicit is usually the way to go, but it can become a problem when you have a public facing API. Every removal you have will be a breaking change, which is not supposed to happen in a public API.
I'm okay with doing this for now, but we might have to rethink this decision in the future, as we don't want to do breaking changes since that will worsen the users' experience

**Comment by rtfpessoa** [comment]
I think keeping them is not a problem and I think we are overthinking the problem here.
IMHO we should just keep things simple and explicit.

**Pull request closed without merging**
