### PR TITLE
bump: api to 33.19.0

### PR DESCRIPTION
**Pull request by joanasteodoro**

### CODE REVIEW

**Comment by joanasteodoro** [comment]
@alerizzo @inesgomas this pipeline's error is quite odd, and i dont see irregular changes in the repo from last months, any idea why this might be happening?

**Comment by alerizzo** [comment]
> @alerizzo @inesgomas this pipeline's error is quite odd, and i dont see irregular changes in the repo from last months, any idea why this might be happening?

There was ONE important change:
image

**Comment by alerizzo** [comment]
@joanasteodoro I'm trying here to revert-and-bump to see if that works: https://github.com/codacy/codacy-api-typescript/pull/215

**Comment by alerizzo** [comment]
So, after fooling around with versions, up to the 33.15.1 works ok, from 33.16.0 it fails. That means that a change in the swagger between those two versions is messing things up.

There were two merge commits between those two versions: [this](https://github.com/codacy/codacy-website/commit/8390828a7384db6d7152451675c670b27e85e959?diff=split&w=1#diff-2678b7fe2ef3aa2749e95bafd98be7bd3c45c2c2007f779249c6d29625871d7d) and [this](https://github.com/codacy/codacy-website/commit/c7c79fe358f24c528ceb2c8f49bddbc8a180e110#diff-2678b7fe2ef3aa2749e95bafd98be7bd3c45c2c2007f779249c6d29625871d7d)

I see nothing so weird, but... I have a feeling about the order of some definitions, so I made some changes to the swagger and here is the PR: https://github.com/codacy/codacy-website/pull/1111

will this fix it? who knows 🤷‍♂️ , but at least we'll discard some things

**Comment by joanasteodoro** [comment]
> So, after fooling around with versions, up to the 33.15.1 works ok, from 33.16.0 it fails. That means that a change in the swagger between those two versions is messing things up.
> 
> There were two merge commits between those two versions: [this](https://github.com/codacy/codacy-website/commit/8390828a7384db6d7152451675c670b27e85e959?diff=split&w=1#diff-2678b7fe2ef3aa2749e95bafd98be7bd3c45c2c2007f779249c6d29625871d7d) and [this](https://github.com/codacy/codacy-website/commit/c7c79fe358f24c528ceb2c8f49bddbc8a180e110#diff-2678b7fe2ef3aa2749e95bafd98be7bd3c45c2c2007f779249c6d29625871d7d)
> 
> I see nothing so weird, but... I have a feeling about the order of some definitions, so I made some changes to the swagger and here is the PR: [codacy/codacy-website#1111](https://github.com/codacy/codacy-website/pull/1111)
> 
> will this fix it? who knows 🤷‍♂️ , but at least we'll discard some things

let's try it, thank you ale ❤️

**Pull request merged**
